FROM gradle:7.4.2-jdk17-alpine AS imageWithDependencies

# We first copy the pom.xml file and the binaries stored in the source repository.
# This way, we retrieve all maven dependencies at the beginning. All these steps will be cached by Docker unless pom.xml or libs/ has been updated.
# This means that we only retrieve all dependencies if we modify the dependencies definition.
RUN mkdir -p /opt/gradle/.gradle
ENV GRADLE_USER_HOME=/opt/gradle/.gradle

COPY ./build.gradle /app/build.gradle
RUN du $HOME/.gradle

WORKDIR /app

RUN gradle clean build --no-daemon --console=verbose || return 0

FROM imageWithDependencies
COPY --from=imageWithDependencies /opt/gradle/.gradle /opt/gradle/.gradle

COPY . /app
WORKDIR /app

RUN sed -i -- 's/localhost:5433/postgresqltest:5432/g' /app/src/test/resources/application.yml
RUN sed -i -- 's/host: 127.0.0.1/host: mongodbtest/g' /app/src/test/resources/application.yml
RUN sed -i -- 's/port: 27018/port: 27017/g' /app/src/test/resources/application.yml
RUN sed -i -- 's/127.0.0.1:390/ldaptest:390/g' /app/src/test/resources/application.yml
CMD gradle :test