spring:
   security:
      saml2:
        relyingparty:
          registration:
            # Our sp-metadata will be served at http://cytomine.local/saml2/sp-metadata/shibboleth
            shibboleth:
              identityprovider:
                singlesignon:
                  sign-request: ${SHIBBOLETH_SSO_SIGN_REQUEST:false}
                metadata-uri: ${SHIBBOLETH_METADATA_URI:https://idp.cytom.in/idp/shibboleth}

              # The private key should not be in PKCS#8 but PKCS#1
              # Generate a 2048-bit RSA Public / Private key pair
              #  openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout private.key -out public.crt
              #
              # Convert the PKCS#8 format private-key to PKCS#1 unencrypted format
              #  openssl rsa -in private.key -out rsaprivate.key
              #
              # You can then set SHIBBOLETH_SP_PRIVATE_KEY=rsaprivate.key and SHIBBOLETH_SP_CERTIFICATE=public.crt
              signing:
                credentials:
                  - private-key-location: ${SHIBBOLETH_SP_PRIVATE_KEY:classpath:local.key}
                    certificate-location: ${SHIBBOLETH_SP_CERTIFICATE:classpath:local.crt}
              decryption:
                credentials:
                  - private-key-location: ${SHIBBOLETH_SP_PRIVATE_KEY:classpath:local.key}
                    certificate-location: ${SHIBBOLETH_SP_CERTIFICATE:classpath:local.crt}
              entity-id: ${SHIBBOLETH_ENTITY_ID:http://cytomine.local/saml2/sp-metadata/shibboleth}
              acs:
                location: ${SHIBBOLETH_ACS_LOCATION:http://cytomine.local/login/saml2/sso/shibboleth}

application:
  authentication:
    saml2:
      shibboleth:
        #attribute's keys shouldn't change as they are used in the code
        attributeMappingFile: ${SHIBBOLETH_ATTRIBUTE_MAPPING_FILE:classpath:shibboleth-attribute-mapping.properties}
        #in case you register more idps, you can add them mapping attribute files here and bind the configuration at be.cytomine.config.properties.Saml2Properties.class

        #these are used from the unit tests of the login method, can be skipped in production
        ssoURI: ${SHIBBOLETH_SSO_URI:https://idp.cytom.in/idp/profile/SAML2/Redirect/SSO?execution=e2s1}
        ssoRedirectURI: ${SHIBBOLETH_SSO_REDIRECT_URI:/idp/profile/SAML2/Redirect/SSO}
server:
  forward-headers-strategy: native