version: "3.4"
services:

  postgresqltest:
    image: registry.cytom.in/cm/rnd/cytomine/tools/envs/postgis:15-3.3-alpine-1.2.0
    container_name: postgres
    restart: unless-stopped
    ports: [ "5432:5432" ]
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

  mongodbtest:
    image: mongo:4.4.18-focal
    container_name: mongodb
    restart: unless-stopped
    ports: [ "27017:27017" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=cytomine

  rabbitmqtest:
    image: rabbitmq:3.10
    container_name: rabbitmq
    ports: [ "5672:5672", "15672:15672" ]
    restart: unless-stopped

  ldaptest:
    image: registry.cytom.in/cm/rnd/cytomine/tools/envs/ldap:0.5.5-0.0.2
    container_name: ldap
    ports: [ "389:389", "636:636" ]
    restart: unless-stopped


